from typing import Optional, Dict

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from src.config import QWEN_MODEL_ID

_tokenizer = None
_model = None


def load_model():
    global _tokenizer, _model

    if _tokenizer is not None and _model is not None:
        return _tokenizer, _model

    print("Loading Qwen...")
    _tokenizer = AutoTokenizer.from_pretrained(QWEN_MODEL_ID)

    _model = AutoModelForCausalLM.from_pretrained(
        QWEN_MODEL_ID,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    )

    if torch.cuda.is_available():
        _model = _model.to("cuda")

    _model.eval()

    print("Qwen loaded.")
    return _tokenizer, _model


def build_messages(
    text: str,
    segments=None,
    semantic_input: Optional[str] = None,
):
    languages = []

    for segment in segments or []:
        lang = segment.get("language", "Unknown")
        if lang != "Unknown" and lang not in languages:
            languages.append(lang)

    detected = ", ".join(languages) if languages else "Unknown"
    semantic = semantic_input or text

    system = (
        "You are MultiMix AI, a multilingual conversational assistant. "
        "The semantic interpretation has already been generated by the "
        "language-processing pipeline. Respond naturally to that meaning. "
        "Do not invent facts. Keep the response concise. "
        "Do not discuss internal processing unless asked."
    )

    user = (
        f"Detected languages: {detected}\n\n"
        f"PRIMARY SEMANTIC INTERPRETATION:\n{semantic}\n\n"
        f"ORIGINAL USER MESSAGE:\n{text}\n\n"
        "Respond to the PRIMARY SEMANTIC INTERPRETATION."
    )

    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def generate_response(
    text: str,
    segments=None,
    semantic_input: Optional[str] = None,
    max_new_tokens: int = 80,
) -> str:
    tokenizer, model = load_model()

    messages = build_messages(
        text=text,
        segments=segments,
        semantic_input=semantic_input,
    )

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512,
    )

    device = next(model.parameters()).device
    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

    generated = output_ids[
        0,
        inputs["input_ids"].shape[1]:,
    ]

    return tokenizer.decode(
        generated,
        skip_special_tokens=True,
    ).strip()


def generate_from_pipeline(
    text: str,
    segments,
    semantic_input: Optional[str] = None,
) -> Dict:
    response = generate_response(
        text=text,
        segments=segments,
        semantic_input=semantic_input,
    )

    languages = sorted({
        s["language"]
        for s in segments
        if s.get("language") != "Unknown"
    })

    return {
        "input": text,
        "languages": languages,
        "response": response,
    }
